#!/usr/bin/env node
/**
 * Regenerates `packages/export-rive/src/keys.generated.ts` from the
 * `rive-app/rive-runtime` C++ runtime's generated headers.
 *
 * Clones the runtime at a pinned commit with a sparse checkout of
 * `include/rive/generated/`, parses every `*_base.hpp` for `typeKey` and
 * `*PropertyKey` constants (see `#export-rive/parse-header.ts`), and emits a
 * single `{ [ClassName]: { typeKey, properties: { name: { key, type } } } }`
 * table.
 *
 * Run with `node packages/export-rive/scripts/generate-keys.ts`.
 */
import { spawnSync } from 'node:child_process';
import { mkdtemp, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { parseBaseHeader, type ClassKeys } from '#export-rive/parse-header.ts';

/** Pinned so re-running the script is reproducible until deliberately bumped. */
const RIVE_RUNTIME_REPO = 'https://github.com/rive-app/rive-runtime.git';
const RIVE_RUNTIME_COMMIT = '2d3eb846aa4e7ed0bb4e3a6303cf6aff8a0fbc02';
const GENERATED_SUBPATH = 'include/rive/generated';

const OUT_FILE = new URL('../src/keys.generated.ts', import.meta.url);

function run(command: string, args: string[], cwd: string): void {
  const result = spawnSync(command, args, { cwd, stdio: 'inherit' });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(' ')} failed with status ${result.status}`);
  }
}

async function listHeaders(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await listHeaders(full)));
    else if (entry.name.endsWith('_base.hpp')) files.push(full);
  }
  return files;
}

async function main(): Promise<void> {
  const workdir = await mkdtemp(join(tmpdir(), 'rive-runtime-'));
  try {
    run('git', ['clone', '--filter=blob:none', '--no-checkout', RIVE_RUNTIME_REPO, workdir], process.cwd());
    run('git', ['sparse-checkout', 'init', '--cone'], workdir);
    run('git', ['sparse-checkout', 'set', GENERATED_SUBPATH], workdir);
    run('git', ['checkout', RIVE_RUNTIME_COMMIT], workdir);

    const headers = await listHeaders(join(workdir, GENERATED_SUBPATH));
    headers.sort();

    const classes: Record<string, ClassKeys> = {};
    for (const path of headers) {
      const source = await readFile(path, 'utf8');
      for (const [name, entry] of Object.entries(parseBaseHeader(source))) {
        if (classes[name] && JSON.stringify(classes[name]) !== JSON.stringify(entry)) {
          throw new Error(`conflicting definitions for class ${name} (${path})`);
        }
        classes[name] = entry;
      }
    }

    const sortedNames = Object.keys(classes).sort();
    const sorted: Record<string, ClassKeys> = {};
    for (const name of sortedNames) sorted[name] = classes[name];

    const body = `// Generated by packages/export-rive/scripts/generate-keys.ts. Do not edit by hand.
// Source: ${RIVE_RUNTIME_REPO} @ ${RIVE_RUNTIME_COMMIT} (${GENERATED_SUBPATH})
import type { ClassKeys } from '#export-rive/parse-header.ts';

export const KEYS: Record<string, ClassKeys> = ${JSON.stringify(sorted, null, 2)};
`;
    await writeFile(OUT_FILE, body);
    console.log(`wrote ${sortedNames.length} classes to ${OUT_FILE.pathname}`);
  } finally {
    await rm(workdir, { recursive: true, force: true });
  }
}

await main();
