// Generated by packages/export-rive/scripts/generate-keys.ts. Do not edit by hand.
// Source: https://github.com/rive-app/rive-runtime.git @ 2d3eb846aa4e7ed0bb4e3a6303cf6aff8a0fbc02 (include/rive/generated)
import type { ClassKeys } from '#export-rive/parse-header.ts';

export const KEYS: Record<string, ClassKeys> = {
  "AdvanceableState": {
    "typeKey": 145,
    "properties": {
      "speed": {
        "key": 292,
        "type": "double"
      }
    }
  },
  "Animation": {
    "typeKey": 27,
    "properties": {
      "name": {
        "key": 55,
        "type": "string"
      }
    }
  },
  "AnimationState": {
    "typeKey": 61,
    "properties": {
      "animationId": {
        "key": 149,
        "type": "uint"
      }
    }
  },
  "AnyState": {
    "typeKey": 62,
    "properties": {}
  },
  "Artboard": {
    "typeKey": 1,
    "properties": {
      "originX": {
        "key": 11,
        "type": "double"
      },
      "originY": {
        "key": 12,
        "type": "double"
      },
      "defaultStateMachineId": {
        "key": 236,
        "type": "uint"
      },
      "viewModelId": {
        "key": 583,
        "type": "uint"
      }
    }
  },
  "ArtboardComponentList": {
    "typeKey": 559,
    "properties": {
      "listSource": {
        "key": 800,
        "type": "uint"
      }
    }
  },
  "ArtboardComponentListOverride": {
    "typeKey": 606,
    "properties": {
      "artboardId": {
        "key": 858,
        "type": "uint"
      },
      "instanceWidth": {
        "key": 859,
        "type": "double"
      },
      "instanceHeight": {
        "key": 860,
        "type": "double"
      },
      "instanceWidthUnitsValue": {
        "key": 856,
        "type": "uint"
      },
      "instanceHeightUnitsValue": {
        "key": 861,
        "type": "uint"
      },
      "instanceWidthScaleType": {
        "key": 862,
        "type": "uint"
      },
      "instanceHeightScaleType": {
        "key": 863,
        "type": "uint"
      }
    }
  },
  "ArtboardListMapRule": {
    "typeKey": 648,
    "properties": {
      "artboardId": {
        "key": 934,
        "type": "uint"
      },
      "viewModelId": {
        "key": 935,
        "type": "uint"
      }
    }
  },
  "Asset": {
    "typeKey": 99,
    "properties": {
      "name": {
        "key": 203,
        "type": "string"
      }
    }
  },
  "AudioAsset": {
    "typeKey": 406,
    "properties": {}
  },
  "AudioEvent": {
    "typeKey": 407,
    "properties": {
      "assetId": {
        "key": 408,
        "type": "uint"
      }
    }
  },
  "Axis": {
    "typeKey": 492,
    "properties": {
      "offset": {
        "key": 675,
        "type": "double"
      },
      "normalized": {
        "key": 676,
        "type": "bool"
      }
    }
  },
  "AxisX": {
    "typeKey": 495,
    "properties": {}
  },
  "AxisY": {
    "typeKey": 494,
    "properties": {}
  },
  "Backboard": {
    "typeKey": 23,
    "properties": {}
  },
  "BindableProperty": {
    "typeKey": 9,
    "properties": {}
  },
  "BindablePropertyArtboard": {
    "typeKey": 597,
    "properties": {}
  },
  "BindablePropertyAsset": {
    "typeKey": 588,
    "properties": {}
  },
  "BindablePropertyBoolean": {
    "typeKey": 472,
    "properties": {
      "propertyValue": {
        "key": 634,
        "type": "bool"
      }
    }
  },
  "BindablePropertyColor": {
    "typeKey": 475,
    "properties": {
      "propertyValue": {
        "key": 638,
        "type": "color"
      }
    }
  },
  "BindablePropertyEnum": {
    "typeKey": 474,
    "properties": {
      "propertyValue": {
        "key": 637,
        "type": "uint"
      }
    }
  },
  "BindablePropertyId": {
    "typeKey": 596,
    "properties": {
      "propertyValue": {
        "key": 823,
        "type": "uint"
      }
    }
  },
  "BindablePropertyInteger": {
    "typeKey": 567,
    "properties": {
      "propertyValue": {
        "key": 686,
        "type": "uint"
      }
    }
  },
  "BindablePropertyList": {
    "typeKey": 590,
    "properties": {
      "propertyValue": {
        "key": 835,
        "type": "uint"
      }
    }
  },
  "BindablePropertyNumber": {
    "typeKey": 473,
    "properties": {
      "propertyValue": {
        "key": 636,
        "type": "double"
      }
    }
  },
  "BindablePropertyString": {
    "typeKey": 471,
    "properties": {
      "propertyValue": {
        "key": 635,
        "type": "string"
      }
    }
  },
  "BindablePropertyTrigger": {
    "typeKey": 503,
    "properties": {}
  },
  "BindablePropertyViewModel": {
    "typeKey": 662,
    "properties": {}
  },
  "BlendAnimation": {
    "typeKey": 74,
    "properties": {
      "animationId": {
        "key": 165,
        "type": "uint"
      }
    }
  },
  "BlendAnimation1D": {
    "typeKey": 75,
    "properties": {
      "value": {
        "key": 166,
        "type": "double"
      }
    }
  },
  "BlendAnimationDirect": {
    "typeKey": 77,
    "properties": {
      "inputId": {
        "key": 168,
        "type": "uint"
      },
      "mixValue": {
        "key": 297,
        "type": "double"
      },
      "blendSource": {
        "key": 298,
        "type": "uint"
      }
    }
  },
  "BlendState": {
    "typeKey": 72,
    "properties": {}
  },
  "BlendState1D": {
    "typeKey": 527,
    "properties": {}
  },
  "BlendState1DInput": {
    "typeKey": 76,
    "properties": {
      "inputId": {
        "key": 167,
        "type": "uint"
      }
    }
  },
  "BlendState1DViewModel": {
    "typeKey": 528,
    "properties": {}
  },
  "BlendStateDirect": {
    "typeKey": 73,
    "properties": {}
  },
  "BlendStateTransition": {
    "typeKey": 78,
    "properties": {
      "exitBlendAnimationId": {
        "key": 171,
        "type": "uint"
      }
    }
  },
  "BlobAsset": {
    "typeKey": 649,
    "properties": {}
  },
  "Bone": {
    "typeKey": 40,
    "properties": {
      "length": {
        "key": 89,
        "type": "double"
      }
    }
  },
  "ClampedScrollPhysics": {
    "typeKey": 524,
    "properties": {}
  },
  "ClippingShape": {
    "typeKey": 42,
    "properties": {
      "sourceId": {
        "key": 92,
        "type": "uint"
      },
      "fillRule": {
        "key": 93,
        "type": "uint"
      },
      "isVisible": {
        "key": 94,
        "type": "bool"
      }
    }
  },
  "Component": {
    "typeKey": 10,
    "properties": {
      "name": {
        "key": 4,
        "type": "string"
      },
      "parentId": {
        "key": 5,
        "type": "uint"
      }
    }
  },
  "ComponentOrigin": {
    "typeKey": 1039,
    "properties": {
      "originX": {
        "key": 1040,
        "type": "double"
      },
      "originY": {
        "key": 1041,
        "type": "double"
      }
    }
  },
  "Constraint": {
    "typeKey": 79,
    "properties": {
      "strength": {
        "key": 172,
        "type": "double"
      }
    }
  },
  "ContainerComponent": {
    "typeKey": 11,
    "properties": {}
  },
  "ContourMeshVertex": {
    "typeKey": 111,
    "properties": {}
  },
  "CubicAsymmetricVertex": {
    "typeKey": 34,
    "properties": {
      "rotation": {
        "key": 79,
        "type": "double"
      },
      "inDistance": {
        "key": 80,
        "type": "double"
      },
      "outDistance": {
        "key": 81,
        "type": "double"
      }
    }
  },
  "CubicDetachedVertex": {
    "typeKey": 6,
    "properties": {
      "inRotation": {
        "key": 84,
        "type": "double"
      },
      "inDistance": {
        "key": 85,
        "type": "double"
      },
      "outRotation": {
        "key": 86,
        "type": "double"
      },
      "outDistance": {
        "key": 87,
        "type": "double"
      }
    }
  },
  "CubicEaseInterpolator": {
    "typeKey": 28,
    "properties": {}
  },
  "CubicInterpolator": {
    "typeKey": 139,
    "properties": {
      "x1": {
        "key": 63,
        "type": "double"
      },
      "y1": {
        "key": 64,
        "type": "double"
      },
      "x2": {
        "key": 65,
        "type": "double"
      },
      "y2": {
        "key": 66,
        "type": "double"
      }
    }
  },
  "CubicInterpolatorComponent": {
    "typeKey": 163,
    "properties": {
      "x1": {
        "key": 337,
        "type": "double"
      },
      "y1": {
        "key": 338,
        "type": "double"
      },
      "x2": {
        "key": 339,
        "type": "double"
      },
      "y2": {
        "key": 340,
        "type": "double"
      }
    }
  },
  "CubicMirroredVertex": {
    "typeKey": 35,
    "properties": {
      "rotation": {
        "key": 82,
        "type": "double"
      },
      "distance": {
        "key": 83,
        "type": "double"
      }
    }
  },
  "CubicValueInterpolator": {
    "typeKey": 138,
    "properties": {}
  },
  "CubicVertex": {
    "typeKey": 36,
    "properties": {}
  },
  "CubicWeight": {
    "typeKey": 46,
    "properties": {
      "inValues": {
        "key": 110,
        "type": "uint"
      },
      "inIndices": {
        "key": 111,
        "type": "uint"
      },
      "outValues": {
        "key": 112,
        "type": "uint"
      },
      "outIndices": {
        "key": 113,
        "type": "uint"
      }
    }
  },
  "CustomProperty": {
    "typeKey": 167,
    "properties": {}
  },
  "CustomPropertyBoolean": {
    "typeKey": 129,
    "properties": {
      "propertyValue": {
        "key": 245,
        "type": "bool"
      }
    }
  },
  "CustomPropertyColor": {
    "typeKey": 592,
    "properties": {
      "propertyValue": {
        "key": 836,
        "type": "color"
      }
    }
  },
  "CustomPropertyEnum": {
    "typeKey": 616,
    "properties": {
      "propertyValue": {
        "key": 872,
        "type": "uint"
      },
      "enumId": {
        "key": 873,
        "type": "uint"
      }
    }
  },
  "CustomPropertyGroup": {
    "typeKey": 548,
    "properties": {}
  },
  "CustomPropertyNumber": {
    "typeKey": 127,
    "properties": {
      "propertyValue": {
        "key": 243,
        "type": "double"
      }
    }
  },
  "CustomPropertyString": {
    "typeKey": 130,
    "properties": {
      "propertyValue": {
        "key": 246,
        "type": "string"
      }
    }
  },
  "CustomPropertyTrigger": {
    "typeKey": 613,
    "properties": {
      "propertyValue": {
        "key": 870,
        "type": "uint"
      }
    }
  },
  "Dash": {
    "typeKey": 507,
    "properties": {
      "length": {
        "key": 692,
        "type": "double"
      },
      "lengthIsPercentage": {
        "key": 693,
        "type": "bool"
      }
    }
  },
  "DashPath": {
    "typeKey": 506,
    "properties": {
      "offset": {
        "key": 690,
        "type": "double"
      },
      "offsetIsPercentage": {
        "key": 691,
        "type": "bool"
      }
    }
  },
  "DataBind": {
    "typeKey": 446,
    "properties": {
      "propertyKey": {
        "key": 586,
        "type": "uint"
      },
      "flags": {
        "key": 587,
        "type": "uint"
      },
      "converterId": {
        "key": 660,
        "type": "uint"
      }
    }
  },
  "DataBindContext": {
    "typeKey": 447,
    "properties": {}
  },
  "DataBindPath": {
    "typeKey": 643,
    "properties": {
      "isRelative": {
        "key": 921,
        "type": "bool"
      }
    }
  },
  "DataConverter": {
    "typeKey": 488,
    "properties": {
      "name": {
        "key": 662,
        "type": "string"
      }
    }
  },
  "DataConverterBooleanNegate": {
    "typeKey": 535,
    "properties": {}
  },
  "DataConverterFormula": {
    "typeKey": 536,
    "properties": {
      "randomModeValue": {
        "key": 887,
        "type": "uint"
      }
    }
  },
  "DataConverterGroup": {
    "typeKey": 499,
    "properties": {}
  },
  "DataConverterGroupItem": {
    "typeKey": 498,
    "properties": {
      "converterId": {
        "key": 679,
        "type": "uint"
      }
    }
  },
  "DataConverterInterpolator": {
    "typeKey": 534,
    "properties": {
      "interpolationType": {
        "key": 757,
        "type": "uint"
      },
      "interpolatorId": {
        "key": 758,
        "type": "uint"
      },
      "duration": {
        "key": 756,
        "type": "double"
      }
    }
  },
  "DataConverterListToLength": {
    "typeKey": 591,
    "properties": {}
  },
  "DataConverterNumberToList": {
    "typeKey": 568,
    "properties": {
      "viewModelId": {
        "key": 816,
        "type": "uint"
      }
    }
  },
  "DataConverterOperation": {
    "typeKey": 516,
    "properties": {
      "operationType": {
        "key": 682,
        "type": "uint"
      }
    }
  },
  "DataConverterOperationValue": {
    "typeKey": 500,
    "properties": {
      "operationValue": {
        "key": 681,
        "type": "double"
      }
    }
  },
  "DataConverterOperationViewModel": {
    "typeKey": 517,
    "properties": {}
  },
  "DataConverterRangeMapper": {
    "typeKey": 519,
    "properties": {
      "interpolationType": {
        "key": 713,
        "type": "uint"
      },
      "interpolatorId": {
        "key": 714,
        "type": "uint"
      },
      "flags": {
        "key": 715,
        "type": "uint"
      },
      "minInput": {
        "key": 716,
        "type": "double"
      },
      "maxInput": {
        "key": 717,
        "type": "double"
      },
      "minOutput": {
        "key": 718,
        "type": "double"
      },
      "maxOutput": {
        "key": 719,
        "type": "double"
      }
    }
  },
  "DataConverterRounder": {
    "typeKey": 489,
    "properties": {
      "decimals": {
        "key": 669,
        "type": "uint"
      }
    }
  },
  "DataConverterStringPad": {
    "typeKey": 530,
    "properties": {
      "length": {
        "key": 743,
        "type": "uint"
      },
      "text": {
        "key": 744,
        "type": "string"
      },
      "padType": {
        "key": 745,
        "type": "uint"
      }
    }
  },
  "DataConverterStringRemoveZeros": {
    "typeKey": 531,
    "properties": {}
  },
  "DataConverterStringTrim": {
    "typeKey": 532,
    "properties": {
      "trimType": {
        "key": 746,
        "type": "uint"
      }
    }
  },
  "DataConverterSystemDegsToRads": {
    "typeKey": 514,
    "properties": {}
  },
  "DataConverterSystemNormalizer": {
    "typeKey": 515,
    "properties": {}
  },
  "DataConverterToNumber": {
    "typeKey": 617,
    "properties": {}
  },
  "DataConverterToString": {
    "typeKey": 490,
    "properties": {
      "flags": {
        "key": 764,
        "type": "uint"
      },
      "decimals": {
        "key": 765,
        "type": "uint"
      },
      "colorFormat": {
        "key": 766,
        "type": "string"
      }
    }
  },
  "DataConverterTrigger": {
    "typeKey": 504,
    "properties": {}
  },
  "DataEnum": {
    "typeKey": 510,
    "properties": {}
  },
  "DataEnumCustom": {
    "typeKey": 438,
    "properties": {
      "name": {
        "key": 572,
        "type": "string"
      }
    }
  },
  "DataEnumSystem": {
    "typeKey": 512,
    "properties": {
      "enumType": {
        "key": 709,
        "type": "uint"
      }
    }
  },
  "DataEnumValue": {
    "typeKey": 445,
    "properties": {
      "key": {
        "key": 578,
        "type": "string"
      },
      "value": {
        "key": 579,
        "type": "string"
      }
    }
  },
  "DistanceConstraint": {
    "typeKey": 82,
    "properties": {
      "distance": {
        "key": 177,
        "type": "double"
      },
      "modeValue": {
        "key": 178,
        "type": "uint"
      }
    }
  },
  "DraggableConstraint": {
    "typeKey": 520,
    "properties": {
      "directionValue": {
        "key": 722,
        "type": "uint"
      }
    }
  },
  "DrawRules": {
    "typeKey": 49,
    "properties": {
      "drawTargetId": {
        "key": 121,
        "type": "uint"
      }
    }
  },
  "DrawTarget": {
    "typeKey": 48,
    "properties": {
      "drawableId": {
        "key": 119,
        "type": "uint"
      },
      "placementValue": {
        "key": 120,
        "type": "uint"
      }
    }
  },
  "Drawable": {
    "typeKey": 13,
    "properties": {
      "blendModeValue": {
        "key": 23,
        "type": "uint"
      },
      "drawableFlags": {
        "key": 129,
        "type": "uint"
      }
    }
  },
  "DrawableAsset": {
    "typeKey": 104,
    "properties": {
      "height": {
        "key": 207,
        "type": "double"
      },
      "width": {
        "key": 208,
        "type": "double"
      }
    }
  },
  "ElasticInterpolator": {
    "typeKey": 174,
    "properties": {
      "easingValue": {
        "key": 405,
        "type": "uint"
      },
      "amplitude": {
        "key": 406,
        "type": "double"
      },
      "period": {
        "key": 407,
        "type": "double"
      }
    }
  },
  "ElasticScrollPhysics": {
    "typeKey": 525,
    "properties": {
      "friction": {
        "key": 728,
        "type": "double"
      },
      "speedMultiplier": {
        "key": 729,
        "type": "double"
      },
      "elasticFactor": {
        "key": 730,
        "type": "double"
      }
    }
  },
  "Ellipse": {
    "typeKey": 4,
    "properties": {}
  },
  "EntryState": {
    "typeKey": 63,
    "properties": {}
  },
  "Event": {
    "typeKey": 128,
    "properties": {}
  },
  "ExitState": {
    "typeKey": 64,
    "properties": {}
  },
  "ExportAudio": {
    "typeKey": 422,
    "properties": {
      "volume": {
        "key": 530,
        "type": "double"
      }
    }
  },
  "Feather": {
    "typeKey": 533,
    "properties": {
      "spaceValue": {
        "key": 748,
        "type": "uint"
      },
      "strength": {
        "key": 749,
        "type": "double"
      },
      "offsetX": {
        "key": 750,
        "type": "double"
      },
      "offsetY": {
        "key": 751,
        "type": "double"
      },
      "inner": {
        "key": 752,
        "type": "bool"
      }
    }
  },
  "FileAsset": {
    "typeKey": 103,
    "properties": {
      "assetId": {
        "key": 204,
        "type": "uint"
      },
      "cdnBaseUrl": {
        "key": 362,
        "type": "string"
      }
    }
  },
  "FileAssetContents": {
    "typeKey": 106,
    "properties": {}
  },
  "Fill": {
    "typeKey": 20,
    "properties": {
      "fillRule": {
        "key": 40,
        "type": "uint"
      }
    }
  },
  "FocusAction": {
    "typeKey": 671,
    "properties": {}
  },
  "FocusActionClear": {
    "typeKey": 1037,
    "properties": {}
  },
  "FocusActionTarget": {
    "typeKey": 652,
    "properties": {
      "targetId": {
        "key": 952,
        "type": "uint"
      }
    }
  },
  "FocusActionTraversal": {
    "typeKey": 672,
    "properties": {
      "traversalKind": {
        "key": 1011,
        "type": "uint"
      }
    }
  },
  "FocusData": {
    "typeKey": 653,
    "properties": {
      "focusFlags": {
        "key": 1033,
        "type": "uint"
      },
      "edgeBehaviorValue": {
        "key": 956,
        "type": "uint"
      }
    }
  },
  "FollowPathConstraint": {
    "typeKey": 165,
    "properties": {
      "distance": {
        "key": 363,
        "type": "double"
      },
      "orient": {
        "key": 364,
        "type": "bool"
      },
      "offset": {
        "key": 365,
        "type": "bool"
      }
    }
  },
  "FontAsset": {
    "typeKey": 141,
    "properties": {}
  },
  "ForegroundLayoutDrawable": {
    "typeKey": 513,
    "properties": {}
  },
  "FormulaToken": {
    "typeKey": 537,
    "properties": {}
  },
  "FormulaTokenArgumentSeparator": {
    "typeKey": 538,
    "properties": {}
  },
  "FormulaTokenFunction": {
    "typeKey": 542,
    "properties": {
      "functionType": {
        "key": 776,
        "type": "uint"
      }
    }
  },
  "FormulaTokenInput": {
    "typeKey": 545,
    "properties": {}
  },
  "FormulaTokenOperation": {
    "typeKey": 541,
    "properties": {
      "operationType": {
        "key": 775,
        "type": "uint"
      }
    }
  },
  "FormulaTokenParenthesis": {
    "typeKey": 539,
    "properties": {}
  },
  "FormulaTokenParenthesisClose": {
    "typeKey": 540,
    "properties": {}
  },
  "FormulaTokenParenthesisOpen": {
    "typeKey": 544,
    "properties": {}
  },
  "FormulaTokenValue": {
    "typeKey": 543,
    "properties": {
      "operationValue": {
        "key": 777,
        "type": "double"
      }
    }
  },
  "GamepadInput": {
    "typeKey": 974,
    "properties": {
      "kind": {
        "key": 1021,
        "type": "uint"
      },
      "mapping": {
        "key": 1018,
        "type": "uint"
      },
      "inputIndex": {
        "key": 1019,
        "type": "uint"
      },
      "buttonPhase": {
        "key": 1020,
        "type": "uint"
      }
    }
  },
  "GradientStop": {
    "typeKey": 19,
    "properties": {
      "colorValue": {
        "key": 38,
        "type": "color"
      },
      "position": {
        "key": 39,
        "type": "double"
      }
    }
  },
  "GridItemPlacement": {
    "typeKey": 1068,
    "properties": {
      "gridColumnSpan": {
        "key": 1049,
        "type": "uint"
      },
      "gridRowSpan": {
        "key": 1050,
        "type": "uint"
      }
    }
  },
  "GridTrack": {
    "typeKey": 1058,
    "properties": {
      "trackValue": {
        "key": 1063,
        "type": "double"
      },
      "trackMaxValue": {
        "key": 1065,
        "type": "double"
      },
      "collection": {
        "key": 1061,
        "type": "uint"
      },
      "trackType": {
        "key": 1062,
        "type": "uint"
      },
      "trackMaxType": {
        "key": 1064,
        "type": "uint"
      }
    }
  },
  "GroupEffect": {
    "typeKey": 645,
    "properties": {}
  },
  "IKConstraint": {
    "typeKey": 81,
    "properties": {
      "invertDirection": {
        "key": 174,
        "type": "bool"
      },
      "parentBoneCount": {
        "key": 175,
        "type": "uint"
      }
    }
  },
  "Image": {
    "typeKey": 100,
    "properties": {
      "assetId": {
        "key": 206,
        "type": "uint"
      },
      "originX": {
        "key": 380,
        "type": "double"
      },
      "originY": {
        "key": 381,
        "type": "double"
      },
      "fit": {
        "key": 974,
        "type": "uint"
      },
      "alignmentX": {
        "key": 975,
        "type": "double"
      },
      "alignmentY": {
        "key": 976,
        "type": "double"
      },
      "samplerFilter": {
        "key": 1076,
        "type": "uint"
      },
      "samplerWrapX": {
        "key": 1077,
        "type": "uint"
      },
      "samplerWrapY": {
        "key": 1078,
        "type": "uint"
      }
    }
  },
  "ImageAsset": {
    "typeKey": 105,
    "properties": {
      "samplerFilter": {
        "key": 1073,
        "type": "uint"
      },
      "samplerWrapX": {
        "key": 1074,
        "type": "uint"
      },
      "samplerWrapY": {
        "key": 1075,
        "type": "uint"
      }
    }
  },
  "InterpolatingKeyFrame": {
    "typeKey": 170,
    "properties": {
      "interpolationType": {
        "key": 68,
        "type": "uint"
      },
      "interpolatorId": {
        "key": 69,
        "type": "uint"
      }
    }
  },
  "Joystick": {
    "typeKey": 148,
    "properties": {
      "x": {
        "key": 299,
        "type": "double"
      },
      "y": {
        "key": 300,
        "type": "double"
      },
      "posX": {
        "key": 303,
        "type": "double"
      },
      "posY": {
        "key": 304,
        "type": "double"
      },
      "originX": {
        "key": 307,
        "type": "double"
      },
      "originY": {
        "key": 308,
        "type": "double"
      },
      "width": {
        "key": 305,
        "type": "double"
      },
      "height": {
        "key": 306,
        "type": "double"
      },
      "xId": {
        "key": 301,
        "type": "uint"
      },
      "yId": {
        "key": 302,
        "type": "uint"
      },
      "joystickFlags": {
        "key": 312,
        "type": "uint"
      },
      "handleSourceId": {
        "key": 313,
        "type": "uint"
      }
    }
  },
  "KeyFrame": {
    "typeKey": 29,
    "properties": {
      "frame": {
        "key": 67,
        "type": "uint"
      }
    }
  },
  "KeyFrameBool": {
    "typeKey": 84,
    "properties": {
      "value": {
        "key": 181,
        "type": "bool"
      }
    }
  },
  "KeyFrameCallback": {
    "typeKey": 171,
    "properties": {}
  },
  "KeyFrameColor": {
    "typeKey": 37,
    "properties": {
      "value": {
        "key": 88,
        "type": "color"
      }
    }
  },
  "KeyFrameDouble": {
    "typeKey": 30,
    "properties": {
      "value": {
        "key": 70,
        "type": "double"
      }
    }
  },
  "KeyFrameId": {
    "typeKey": 50,
    "properties": {
      "value": {
        "key": 122,
        "type": "uint"
      }
    }
  },
  "KeyFrameInt": {
    "typeKey": 1067,
    "properties": {}
  },
  "KeyFrameInterpolator": {
    "typeKey": 175,
    "properties": {}
  },
  "KeyFrameString": {
    "typeKey": 142,
    "properties": {
      "value": {
        "key": 280,
        "type": "string"
      }
    }
  },
  "KeyFrameUint": {
    "typeKey": 450,
    "properties": {
      "value": {
        "key": 631,
        "type": "uint"
      }
    }
  },
  "KeyboardInput": {
    "typeKey": 664,
    "properties": {
      "keyType": {
        "key": 971,
        "type": "uint"
      },
      "keyPhase": {
        "key": 972,
        "type": "uint"
      },
      "modifiers": {
        "key": 973,
        "type": "uint"
      }
    }
  },
  "KeyedObject": {
    "typeKey": 25,
    "properties": {
      "objectId": {
        "key": 51,
        "type": "uint"
      }
    }
  },
  "KeyedProperty": {
    "typeKey": 26,
    "properties": {
      "propertyKey": {
        "key": 53,
        "type": "uint"
      }
    }
  },
  "LayerState": {
    "typeKey": 60,
    "properties": {
      "flags": {
        "key": 536,
        "type": "uint"
      }
    }
  },
  "LayoutComponent": {
    "typeKey": 409,
    "properties": {
      "clip": {
        "key": 196,
        "type": "bool"
      },
      "width": {
        "key": 7,
        "type": "double"
      },
      "height": {
        "key": 8,
        "type": "double"
      },
      "styleId": {
        "key": 494,
        "type": "uint"
      },
      "fractionalWidth": {
        "key": 706,
        "type": "double"
      },
      "fractionalHeight": {
        "key": 707,
        "type": "double"
      }
    }
  },
  "LayoutComponentStyle": {
    "typeKey": 420,
    "properties": {
      "gapHorizontal": {
        "key": 498,
        "type": "double"
      },
      "gapVertical": {
        "key": 499,
        "type": "double"
      },
      "borderLeft": {
        "key": 504,
        "type": "double"
      },
      "borderRight": {
        "key": 505,
        "type": "double"
      },
      "borderTop": {
        "key": 506,
        "type": "double"
      },
      "borderBottom": {
        "key": 507,
        "type": "double"
      },
      "marginLeft": {
        "key": 508,
        "type": "double"
      },
      "marginRight": {
        "key": 509,
        "type": "double"
      },
      "marginTop": {
        "key": 510,
        "type": "double"
      },
      "marginBottom": {
        "key": 511,
        "type": "double"
      },
      "paddingLeft": {
        "key": 512,
        "type": "double"
      },
      "paddingRight": {
        "key": 513,
        "type": "double"
      },
      "paddingTop": {
        "key": 514,
        "type": "double"
      },
      "paddingBottom": {
        "key": 515,
        "type": "double"
      },
      "positionLeft": {
        "key": 516,
        "type": "double"
      },
      "positionRight": {
        "key": 517,
        "type": "double"
      },
      "positionTop": {
        "key": 518,
        "type": "double"
      },
      "positionBottom": {
        "key": 519,
        "type": "double"
      },
      "positionLeftUnitsValue": {
        "key": 621,
        "type": "uint"
      },
      "positionRightUnitsValue": {
        "key": 622,
        "type": "uint"
      },
      "positionTopUnitsValue": {
        "key": 623,
        "type": "uint"
      },
      "positionBottomUnitsValue": {
        "key": 624,
        "type": "uint"
      },
      "flexBasis": {
        "key": 523,
        "type": "double"
      },
      "aspectRatio": {
        "key": 524,
        "type": "double"
      },
      "interpolatorId": {
        "key": 591,
        "type": "uint"
      },
      "interpolationTime": {
        "key": 592,
        "type": "double"
      },
      "flexBasisUnitsValue": {
        "key": 705,
        "type": "uint"
      },
      "layoutAlignmentType": {
        "key": 632,
        "type": "uint"
      },
      "animationStyleType": {
        "key": 589,
        "type": "uint"
      },
      "interpolationType": {
        "key": 590,
        "type": "uint"
      },
      "positionTypeValue": {
        "key": 597,
        "type": "uint"
      },
      "flexDirectionValue": {
        "key": 598,
        "type": "uint"
      },
      "directionValue": {
        "key": 599,
        "type": "uint"
      },
      "flexWrapValue": {
        "key": 604,
        "type": "uint"
      },
      "overflowValue": {
        "key": 605,
        "type": "uint"
      },
      "intrinsicallySizedValue": {
        "key": 606,
        "type": "bool"
      },
      "borderLeftUnitsValue": {
        "key": 609,
        "type": "uint"
      },
      "borderRightUnitsValue": {
        "key": 610,
        "type": "uint"
      },
      "borderTopUnitsValue": {
        "key": 611,
        "type": "uint"
      },
      "borderBottomUnitsValue": {
        "key": 612,
        "type": "uint"
      },
      "marginLeftUnitsValue": {
        "key": 613,
        "type": "uint"
      },
      "marginRightUnitsValue": {
        "key": 614,
        "type": "uint"
      },
      "marginTopUnitsValue": {
        "key": 615,
        "type": "uint"
      },
      "marginBottomUnitsValue": {
        "key": 616,
        "type": "uint"
      },
      "paddingLeftUnitsValue": {
        "key": 617,
        "type": "uint"
      },
      "paddingRightUnitsValue": {
        "key": 618,
        "type": "uint"
      },
      "paddingTopUnitsValue": {
        "key": 619,
        "type": "uint"
      },
      "paddingBottomUnitsValue": {
        "key": 620,
        "type": "uint"
      },
      "gapHorizontalUnitsValue": {
        "key": 625,
        "type": "uint"
      },
      "gapVerticalUnitsValue": {
        "key": 626,
        "type": "uint"
      },
      "justifyItemsValue": {
        "key": 1045,
        "type": "uint"
      },
      "layoutTypeValue": {
        "key": 1059,
        "type": "uint"
      },
      "linkCornerRadius": {
        "key": 639,
        "type": "bool"
      },
      "cornerRadiusTL": {
        "key": 640,
        "type": "double"
      },
      "cornerRadiusTR": {
        "key": 641,
        "type": "double"
      },
      "cornerRadiusBL": {
        "key": 642,
        "type": "double"
      },
      "cornerRadiusBR": {
        "key": 643,
        "type": "double"
      }
    }
  },
  "LayoutNodeStyle": {
    "typeKey": 1057,
    "properties": {
      "width": {
        "key": 1066,
        "type": "double"
      },
      "height": {
        "key": 1067,
        "type": "double"
      },
      "fractionalWidth": {
        "key": 1057,
        "type": "double"
      },
      "fractionalHeight": {
        "key": 1058,
        "type": "double"
      }
    }
  },
  "LayoutParticipant": {
    "typeKey": 1066,
    "properties": {}
  },
  "LayoutSizingStyle": {
    "typeKey": 1056,
    "properties": {
      "minWidth": {
        "key": 502,
        "type": "double"
      },
      "maxWidth": {
        "key": 500,
        "type": "double"
      },
      "minHeight": {
        "key": 503,
        "type": "double"
      },
      "maxHeight": {
        "key": 501,
        "type": "double"
      },
      "minWidthUnitsValue": {
        "key": 627,
        "type": "uint"
      },
      "maxWidthUnitsValue": {
        "key": 629,
        "type": "uint"
      },
      "minHeightUnitsValue": {
        "key": 628,
        "type": "uint"
      },
      "maxHeightUnitsValue": {
        "key": 630,
        "type": "uint"
      },
      "layoutWidthScaleType": {
        "key": 655,
        "type": "uint"
      },
      "layoutHeightScaleType": {
        "key": 656,
        "type": "uint"
      },
      "widthUnitsValue": {
        "key": 607,
        "type": "uint"
      },
      "heightUnitsValue": {
        "key": 608,
        "type": "uint"
      },
      "justifySelfValue": {
        "key": 1046,
        "type": "uint"
      },
      "displayValue": {
        "key": 596,
        "type": "uint"
      }
    }
  },
  "LinearAnimation": {
    "typeKey": 31,
    "properties": {
      "fps": {
        "key": 56,
        "type": "uint"
      },
      "duration": {
        "key": 57,
        "type": "uint"
      },
      "speed": {
        "key": 58,
        "type": "double"
      },
      "loopValue": {
        "key": 59,
        "type": "uint"
      },
      "workStart": {
        "key": 60,
        "type": "uint"
      },
      "workEnd": {
        "key": 61,
        "type": "uint"
      },
      "enableWorkArea": {
        "key": 62,
        "type": "bool"
      },
      "quantize": {
        "key": 376,
        "type": "bool"
      }
    }
  },
  "LinearGradient": {
    "typeKey": 22,
    "properties": {
      "startX": {
        "key": 42,
        "type": "double"
      },
      "startY": {
        "key": 33,
        "type": "double"
      },
      "endX": {
        "key": 34,
        "type": "double"
      },
      "endY": {
        "key": 35,
        "type": "double"
      },
      "opacity": {
        "key": 46,
        "type": "double"
      }
    }
  },
  "ListFollowPathConstraint": {
    "typeKey": 625,
    "properties": {
      "distanceEnd": {
        "key": 888,
        "type": "double"
      },
      "distanceOffset": {
        "key": 889,
        "type": "double"
      }
    }
  },
  "ListPath": {
    "typeKey": 619,
    "properties": {
      "listSource": {
        "key": 874,
        "type": "uint"
      }
    }
  },
  "ListenerAction": {
    "typeKey": 125,
    "properties": {
      "flags": {
        "key": 980,
        "type": "uint"
      }
    }
  },
  "ListenerAlignTarget": {
    "typeKey": 126,
    "properties": {
      "targetId": {
        "key": 240,
        "type": "uint"
      },
      "preserveOffset": {
        "key": 541,
        "type": "bool"
      }
    }
  },
  "ListenerBoolChange": {
    "typeKey": 117,
    "properties": {
      "value": {
        "key": 228,
        "type": "uint"
      }
    }
  },
  "ListenerFireEvent": {
    "typeKey": 168,
    "properties": {
      "eventId": {
        "key": 389,
        "type": "uint"
      }
    }
  },
  "ListenerInputChange": {
    "typeKey": 116,
    "properties": {
      "inputId": {
        "key": 227,
        "type": "uint"
      },
      "nestedInputId": {
        "key": 400,
        "type": "uint"
      }
    }
  },
  "ListenerInputType": {
    "typeKey": 658,
    "properties": {
      "listenerTypeValue": {
        "key": 965,
        "type": "uint"
      }
    }
  },
  "ListenerInputTypeEvent": {
    "typeKey": 659,
    "properties": {
      "eventId": {
        "key": 962,
        "type": "uint"
      }
    }
  },
  "ListenerInputTypeGamepad": {
    "typeKey": 973,
    "properties": {}
  },
  "ListenerInputTypeKeyboard": {
    "typeKey": 665,
    "properties": {}
  },
  "ListenerInputTypeSemantic": {
    "typeKey": 669,
    "properties": {}
  },
  "ListenerInputTypeText": {
    "typeKey": 666,
    "properties": {}
  },
  "ListenerInputTypeViewModel": {
    "typeKey": 660,
    "properties": {}
  },
  "ListenerNumberChange": {
    "typeKey": 118,
    "properties": {
      "value": {
        "key": 229,
        "type": "double"
      }
    }
  },
  "ListenerTriggerChange": {
    "typeKey": 115,
    "properties": {}
  },
  "ListenerViewModelChange": {
    "typeKey": 487,
    "properties": {}
  },
  "ManifestAsset": {
    "typeKey": 642,
    "properties": {}
  },
  "Mesh": {
    "typeKey": 109,
    "properties": {}
  },
  "MeshVertex": {
    "typeKey": 108,
    "properties": {
      "u": {
        "key": 215,
        "type": "double"
      },
      "v": {
        "key": 216,
        "type": "double"
      }
    }
  },
  "NSlicedNode": {
    "typeKey": 508,
    "properties": {
      "initialWidth": {
        "key": 697,
        "type": "double"
      },
      "initialHeight": {
        "key": 698,
        "type": "double"
      },
      "width": {
        "key": 699,
        "type": "double"
      },
      "height": {
        "key": 700,
        "type": "double"
      }
    }
  },
  "NSlicer": {
    "typeKey": 493,
    "properties": {}
  },
  "NSlicerTileMode": {
    "typeKey": 491,
    "properties": {
      "patchIndex": {
        "key": 672,
        "type": "uint"
      },
      "style": {
        "key": 673,
        "type": "uint"
      }
    }
  },
  "NestedAnimation": {
    "typeKey": 93,
    "properties": {
      "animationId": {
        "key": 198,
        "type": "uint"
      }
    }
  },
  "NestedArtboard": {
    "typeKey": 92,
    "properties": {
      "artboardId": {
        "key": 197,
        "type": "uint"
      },
      "isPaused": {
        "key": 895,
        "type": "bool"
      },
      "speed": {
        "key": 907,
        "type": "double"
      },
      "quantize": {
        "key": 908,
        "type": "double"
      },
      "isStateful": {
        "key": 1014,
        "type": "bool"
      }
    }
  },
  "NestedArtboardLayout": {
    "typeKey": 452,
    "properties": {
      "instanceWidth": {
        "key": 663,
        "type": "double"
      },
      "instanceHeight": {
        "key": 664,
        "type": "double"
      },
      "instanceWidthUnitsValue": {
        "key": 665,
        "type": "uint"
      },
      "instanceHeightUnitsValue": {
        "key": 666,
        "type": "uint"
      },
      "instanceWidthScaleType": {
        "key": 667,
        "type": "uint"
      },
      "instanceHeightScaleType": {
        "key": 668,
        "type": "uint"
      }
    }
  },
  "NestedArtboardLeaf": {
    "typeKey": 451,
    "properties": {
      "fit": {
        "key": 538,
        "type": "uint"
      },
      "fitToLayoutParent": {
        "key": 1098,
        "type": "bool"
      },
      "alignmentX": {
        "key": 644,
        "type": "double"
      },
      "alignmentY": {
        "key": 645,
        "type": "double"
      }
    }
  },
  "NestedBool": {
    "typeKey": 123,
    "properties": {
      "nestedValue": {
        "key": 238,
        "type": "bool"
      }
    }
  },
  "NestedInput": {
    "typeKey": 121,
    "properties": {
      "inputId": {
        "key": 237,
        "type": "uint"
      }
    }
  },
  "NestedLinearAnimation": {
    "typeKey": 97,
    "properties": {
      "mix": {
        "key": 200,
        "type": "double"
      }
    }
  },
  "NestedNumber": {
    "typeKey": 124,
    "properties": {
      "nestedValue": {
        "key": 239,
        "type": "double"
      }
    }
  },
  "NestedRemapAnimation": {
    "typeKey": 98,
    "properties": {
      "time": {
        "key": 202,
        "type": "double"
      }
    }
  },
  "NestedSimpleAnimation": {
    "typeKey": 96,
    "properties": {
      "speed": {
        "key": 199,
        "type": "double"
      },
      "isPlaying": {
        "key": 201,
        "type": "bool"
      }
    }
  },
  "NestedStateMachine": {
    "typeKey": 95,
    "properties": {}
  },
  "NestedTrigger": {
    "typeKey": 122,
    "properties": {}
  },
  "Node": {
    "typeKey": 2,
    "properties": {
      "x": {
        "key": 13,
        "type": "double"
      },
      "y": {
        "key": 14,
        "type": "double"
      }
    }
  },
  "OpenUrlEvent": {
    "typeKey": 131,
    "properties": {
      "url": {
        "key": 248,
        "type": "string"
      },
      "targetValue": {
        "key": 249,
        "type": "uint"
      }
    }
  },
  "ParametricPath": {
    "typeKey": 15,
    "properties": {
      "width": {
        "key": 20,
        "type": "double"
      },
      "height": {
        "key": 21,
        "type": "double"
      },
      "originX": {
        "key": 123,
        "type": "double"
      },
      "originY": {
        "key": 124,
        "type": "double"
      }
    }
  },
  "Path": {
    "typeKey": 12,
    "properties": {
      "pathFlags": {
        "key": 128,
        "type": "uint"
      },
      "isHole": {
        "key": 770,
        "type": "bool"
      }
    }
  },
  "PathVertex": {
    "typeKey": 14,
    "properties": {}
  },
  "PointsCommonPath": {
    "typeKey": 620,
    "properties": {
      "isClosed": {
        "key": 32,
        "type": "bool"
      }
    }
  },
  "PointsPath": {
    "typeKey": 16,
    "properties": {}
  },
  "Polygon": {
    "typeKey": 51,
    "properties": {
      "points": {
        "key": 125,
        "type": "uint"
      },
      "cornerRadius": {
        "key": 126,
        "type": "double"
      }
    }
  },
  "RadialGradient": {
    "typeKey": 17,
    "properties": {}
  },
  "Rectangle": {
    "typeKey": 7,
    "properties": {
      "linkCornerRadius": {
        "key": 164,
        "type": "bool"
      },
      "cornerRadiusTL": {
        "key": 31,
        "type": "double"
      },
      "cornerRadiusTR": {
        "key": 161,
        "type": "double"
      },
      "cornerRadiusBL": {
        "key": 162,
        "type": "double"
      },
      "cornerRadiusBR": {
        "key": 163,
        "type": "double"
      }
    }
  },
  "RootBone": {
    "typeKey": 41,
    "properties": {
      "x": {
        "key": 90,
        "type": "double"
      },
      "y": {
        "key": 91,
        "type": "double"
      }
    }
  },
  "RotationConstraint": {
    "typeKey": 89,
    "properties": {}
  },
  "ScaleConstraint": {
    "typeKey": 88,
    "properties": {}
  },
  "ScriptAsset": {
    "typeKey": 529,
    "properties": {
      "generatorFunctionRef": {
        "key": 893,
        "type": "uint"
      },
      "isModule": {
        "key": 914,
        "type": "bool"
      },
      "serializedImplementedMethods": {
        "key": 1022,
        "type": "uint"
      }
    }
  },
  "ScriptInputArtboard": {
    "typeKey": 621,
    "properties": {
      "artboardId": {
        "key": 876,
        "type": "uint"
      }
    }
  },
  "ScriptInputBoolean": {
    "typeKey": 631,
    "properties": {}
  },
  "ScriptInputColor": {
    "typeKey": 626,
    "properties": {}
  },
  "ScriptInputNumber": {
    "typeKey": 611,
    "properties": {}
  },
  "ScriptInputString": {
    "typeKey": 627,
    "properties": {}
  },
  "ScriptInputTrigger": {
    "typeKey": 618,
    "properties": {}
  },
  "ScriptInputViewModelProperty": {
    "typeKey": 612,
    "properties": {}
  },
  "ScriptModuleAsset": {
    "typeKey": 1071,
    "properties": {
      "language": {
        "key": 1087,
        "type": "uint"
      }
    }
  },
  "ScriptedDataConverter": {
    "typeKey": 629,
    "properties": {
      "scriptAssetId": {
        "key": 892,
        "type": "uint"
      }
    }
  },
  "ScriptedDrawable": {
    "typeKey": 603,
    "properties": {
      "scriptAssetId": {
        "key": 848,
        "type": "uint"
      }
    }
  },
  "ScriptedInterpolator": {
    "typeKey": 972,
    "properties": {
      "scriptAssetId": {
        "key": 1015,
        "type": "uint"
      }
    }
  },
  "ScriptedLayout": {
    "typeKey": 637,
    "properties": {}
  },
  "ScriptedListenerAction": {
    "typeKey": 646,
    "properties": {
      "scriptAssetId": {
        "key": 930,
        "type": "uint"
      }
    }
  },
  "ScriptedPathEffect": {
    "typeKey": 640,
    "properties": {
      "scriptAssetId": {
        "key": 912,
        "type": "uint"
      }
    }
  },
  "ScriptedTransitionCondition": {
    "typeKey": 647,
    "properties": {
      "scriptAssetId": {
        "key": 931,
        "type": "uint"
      }
    }
  },
  "ScrollBarConstraint": {
    "typeKey": 522,
    "properties": {
      "scrollConstraintId": {
        "key": 725,
        "type": "uint"
      },
      "autoSize": {
        "key": 734,
        "type": "bool"
      }
    }
  },
  "ScrollConstraint": {
    "typeKey": 521,
    "properties": {
      "scrollOffsetX": {
        "key": 759,
        "type": "double"
      },
      "scrollOffsetY": {
        "key": 760,
        "type": "double"
      },
      "snap": {
        "key": 724,
        "type": "bool"
      },
      "physicsTypeValue": {
        "key": 727,
        "type": "uint"
      },
      "physicsId": {
        "key": 726,
        "type": "uint"
      },
      "virtualize": {
        "key": 850,
        "type": "bool"
      },
      "virtualizeBuffer": {
        "key": 221,
        "type": "uint"
      },
      "infinite": {
        "key": 851,
        "type": "bool"
      },
      "interactive": {
        "key": 891,
        "type": "bool"
      },
      "threshold": {
        "key": 894,
        "type": "double"
      },
      "dragMultiplier": {
        "key": 1029,
        "type": "double"
      }
    }
  },
  "ScrollPhysics": {
    "typeKey": 523,
    "properties": {
      "constraintId": {
        "key": 731,
        "type": "uint"
      }
    }
  },
  "SemanticData": {
    "typeKey": 668,
    "properties": {
      "role": {
        "key": 982,
        "type": "uint"
      },
      "label": {
        "key": 983,
        "type": "string"
      },
      "value": {
        "key": 984,
        "type": "string"
      },
      "hint": {
        "key": 985,
        "type": "string"
      },
      "headingLevel": {
        "key": 986,
        "type": "uint"
      },
      "traitFlags": {
        "key": 987,
        "type": "uint"
      },
      "stateFlags": {
        "key": 988,
        "type": "uint"
      }
    }
  },
  "SemanticInput": {
    "typeKey": 670,
    "properties": {
      "actionType": {
        "key": 1010,
        "type": "uint"
      }
    }
  },
  "ShaderAsset": {
    "typeKey": 970,
    "properties": {}
  },
  "Shape": {
    "typeKey": 3,
    "properties": {}
  },
  "ShapePaint": {
    "typeKey": 21,
    "properties": {
      "isVisible": {
        "key": 41,
        "type": "bool"
      },
      "blendModeValue": {
        "key": 747,
        "type": "uint"
      }
    }
  },
  "SkeletalComponent": {
    "typeKey": 39,
    "properties": {}
  },
  "Skin": {
    "typeKey": 43,
    "properties": {
      "xx": {
        "key": 104,
        "type": "double"
      },
      "yx": {
        "key": 105,
        "type": "double"
      },
      "xy": {
        "key": 106,
        "type": "double"
      },
      "yy": {
        "key": 107,
        "type": "double"
      },
      "tx": {
        "key": 108,
        "type": "double"
      },
      "ty": {
        "key": 109,
        "type": "double"
      }
    }
  },
  "SolidColor": {
    "typeKey": 18,
    "properties": {
      "colorValue": {
        "key": 37,
        "type": "color"
      }
    }
  },
  "Solo": {
    "typeKey": 147,
    "properties": {
      "activeComponentId": {
        "key": 296,
        "type": "uint"
      }
    }
  },
  "Star": {
    "typeKey": 52,
    "properties": {
      "innerRadius": {
        "key": 127,
        "type": "double"
      }
    }
  },
  "StateMachine": {
    "typeKey": 53,
    "properties": {}
  },
  "StateMachineBool": {
    "typeKey": 59,
    "properties": {
      "value": {
        "key": 141,
        "type": "bool"
      }
    }
  },
  "StateMachineComponent": {
    "typeKey": 54,
    "properties": {
      "name": {
        "key": 138,
        "type": "string"
      }
    }
  },
  "StateMachineFireAction": {
    "typeKey": 615,
    "properties": {
      "occursValue": {
        "key": 393,
        "type": "uint"
      }
    }
  },
  "StateMachineFireEvent": {
    "typeKey": 169,
    "properties": {
      "eventId": {
        "key": 392,
        "type": "uint"
      }
    }
  },
  "StateMachineFireTrigger": {
    "typeKey": 614,
    "properties": {}
  },
  "StateMachineInput": {
    "typeKey": 55,
    "properties": {}
  },
  "StateMachineLayer": {
    "typeKey": 57,
    "properties": {}
  },
  "StateMachineLayerComponent": {
    "typeKey": 66,
    "properties": {}
  },
  "StateMachineListener": {
    "typeKey": 654,
    "properties": {
      "targetId": {
        "key": 224,
        "type": "uint"
      }
    }
  },
  "StateMachineListenerSingle": {
    "typeKey": 114,
    "properties": {
      "listenerTypeValue": {
        "key": 225,
        "type": "uint"
      },
      "eventId": {
        "key": 399,
        "type": "uint"
      }
    }
  },
  "StateMachineNumber": {
    "typeKey": 56,
    "properties": {
      "value": {
        "key": 140,
        "type": "double"
      }
    }
  },
  "StateMachineTrigger": {
    "typeKey": 58,
    "properties": {}
  },
  "StateTransition": {
    "typeKey": 65,
    "properties": {
      "stateToId": {
        "key": 151,
        "type": "uint"
      },
      "flags": {
        "key": 152,
        "type": "uint"
      },
      "duration": {
        "key": 158,
        "type": "uint"
      },
      "exitTime": {
        "key": 160,
        "type": "uint"
      },
      "interpolationType": {
        "key": 349,
        "type": "uint"
      },
      "interpolatorId": {
        "key": 350,
        "type": "uint"
      },
      "randomWeight": {
        "key": 537,
        "type": "uint"
      }
    }
  },
  "StraightVertex": {
    "typeKey": 5,
    "properties": {
      "radius": {
        "key": 26,
        "type": "double"
      }
    }
  },
  "Stroke": {
    "typeKey": 24,
    "properties": {
      "thickness": {
        "key": 47,
        "type": "double"
      },
      "cap": {
        "key": 48,
        "type": "uint"
      },
      "join": {
        "key": 49,
        "type": "uint"
      },
      "transformAffectsStroke": {
        "key": 50,
        "type": "bool"
      }
    }
  },
  "TargetEffect": {
    "typeKey": 644,
    "properties": {
      "targetId": {
        "key": 922,
        "type": "uint"
      }
    }
  },
  "TargetedConstraint": {
    "typeKey": 80,
    "properties": {
      "targetId": {
        "key": 173,
        "type": "uint"
      }
    }
  },
  "Tendon": {
    "typeKey": 44,
    "properties": {
      "boneId": {
        "key": 95,
        "type": "uint"
      },
      "xx": {
        "key": 96,
        "type": "double"
      },
      "yx": {
        "key": 97,
        "type": "double"
      },
      "xy": {
        "key": 98,
        "type": "double"
      },
      "yy": {
        "key": 99,
        "type": "double"
      },
      "tx": {
        "key": 100,
        "type": "double"
      },
      "ty": {
        "key": 101,
        "type": "double"
      }
    }
  },
  "Text": {
    "typeKey": 134,
    "properties": {
      "alignValue": {
        "key": 281,
        "type": "uint"
      },
      "sizingValue": {
        "key": 284,
        "type": "uint"
      },
      "overflowValue": {
        "key": 287,
        "type": "uint"
      },
      "width": {
        "key": 285,
        "type": "double"
      },
      "height": {
        "key": 286,
        "type": "double"
      },
      "originX": {
        "key": 366,
        "type": "double"
      },
      "originY": {
        "key": 367,
        "type": "double"
      },
      "paragraphSpacing": {
        "key": 371,
        "type": "double"
      },
      "originValue": {
        "key": 377,
        "type": "uint"
      },
      "wrapValue": {
        "key": 683,
        "type": "uint"
      },
      "verticalAlignValue": {
        "key": 685,
        "type": "uint"
      },
      "fitFromBaseline": {
        "key": 703,
        "type": "bool"
      },
      "textRunListSource": {
        "key": 932,
        "type": "uint"
      },
      "verticalTrimValue": {
        "key": 1026,
        "type": "uint"
      }
    }
  },
  "TextAsset": {
    "typeKey": 971,
    "properties": {
      "folderPath": {
        "key": 926,
        "type": "string"
      }
    }
  },
  "TextFollowPathModifier": {
    "typeKey": 547,
    "properties": {
      "radial": {
        "key": 779,
        "type": "bool"
      },
      "orient": {
        "key": 782,
        "type": "bool"
      },
      "start": {
        "key": 783,
        "type": "double"
      },
      "end": {
        "key": 784,
        "type": "double"
      },
      "strength": {
        "key": 785,
        "type": "double"
      },
      "offset": {
        "key": 786,
        "type": "double"
      }
    }
  },
  "TextInput": {
    "typeKey": 569,
    "properties": {
      "text": {
        "key": 817,
        "type": "string"
      },
      "selectionRadius": {
        "key": 818,
        "type": "double"
      },
      "multiline": {
        "key": 979,
        "type": "bool"
      },
      "alignValue": {
        "key": 222,
        "type": "uint"
      },
      "verticalAlignValue": {
        "key": 1094,
        "type": "uint"
      },
      "obscured": {
        "key": 1095,
        "type": "bool"
      }
    }
  },
  "TextInputCursor": {
    "typeKey": 571,
    "properties": {}
  },
  "TextInputDrawable": {
    "typeKey": 570,
    "properties": {}
  },
  "TextInputSelectedText": {
    "typeKey": 575,
    "properties": {}
  },
  "TextInputSelection": {
    "typeKey": 574,
    "properties": {}
  },
  "TextInputText": {
    "typeKey": 572,
    "properties": {}
  },
  "TextModifier": {
    "typeKey": 160,
    "properties": {}
  },
  "TextModifierGroup": {
    "typeKey": 159,
    "properties": {
      "modifierFlags": {
        "key": 335,
        "type": "uint"
      },
      "originX": {
        "key": 328,
        "type": "double"
      },
      "originY": {
        "key": 329,
        "type": "double"
      },
      "opacity": {
        "key": 324,
        "type": "double"
      },
      "x": {
        "key": 322,
        "type": "double"
      },
      "y": {
        "key": 323,
        "type": "double"
      },
      "rotation": {
        "key": 332,
        "type": "double"
      },
      "scaleX": {
        "key": 330,
        "type": "double"
      },
      "scaleY": {
        "key": 331,
        "type": "double"
      }
    }
  },
  "TextModifierRange": {
    "typeKey": 158,
    "properties": {
      "modifyFrom": {
        "key": 327,
        "type": "double"
      },
      "modifyTo": {
        "key": 336,
        "type": "double"
      },
      "strength": {
        "key": 334,
        "type": "double"
      },
      "unitsValue": {
        "key": 316,
        "type": "uint"
      },
      "typeValue": {
        "key": 325,
        "type": "uint"
      },
      "modeValue": {
        "key": 326,
        "type": "uint"
      },
      "clamp": {
        "key": 333,
        "type": "bool"
      },
      "falloffFrom": {
        "key": 317,
        "type": "double"
      },
      "falloffTo": {
        "key": 318,
        "type": "double"
      },
      "offset": {
        "key": 319,
        "type": "double"
      },
      "runId": {
        "key": 378,
        "type": "uint"
      }
    }
  },
  "TextShapeModifier": {
    "typeKey": 161,
    "properties": {}
  },
  "TextStyle": {
    "typeKey": 573,
    "properties": {
      "fontSize": {
        "key": 274,
        "type": "double"
      },
      "lineHeight": {
        "key": 370,
        "type": "double"
      },
      "letterSpacing": {
        "key": 390,
        "type": "double"
      },
      "fontAssetId": {
        "key": 279,
        "type": "uint"
      }
    }
  },
  "TextStyleAxis": {
    "typeKey": 144,
    "properties": {
      "tag": {
        "key": 289,
        "type": "uint"
      },
      "axisValue": {
        "key": 288,
        "type": "double"
      }
    }
  },
  "TextStyleBackground": {
    "typeKey": 1069,
    "properties": {
      "cornerRadius": {
        "key": 1071,
        "type": "double"
      }
    }
  },
  "TextStyleFeature": {
    "typeKey": 164,
    "properties": {
      "tag": {
        "key": 356,
        "type": "uint"
      },
      "featureValue": {
        "key": 357,
        "type": "uint"
      }
    }
  },
  "TextStylePaint": {
    "typeKey": 137,
    "properties": {}
  },
  "TextTargetModifier": {
    "typeKey": 546,
    "properties": {
      "targetId": {
        "key": 778,
        "type": "uint"
      }
    }
  },
  "TextValueRun": {
    "typeKey": 135,
    "properties": {
      "styleId": {
        "key": 272,
        "type": "uint"
      },
      "text": {
        "key": 268,
        "type": "string"
      }
    }
  },
  "TextVariationModifier": {
    "typeKey": 162,
    "properties": {
      "axisTag": {
        "key": 320,
        "type": "uint"
      },
      "axisValue": {
        "key": 321,
        "type": "double"
      }
    }
  },
  "TransformComponent": {
    "typeKey": 38,
    "properties": {
      "rotation": {
        "key": 15,
        "type": "double"
      },
      "scaleX": {
        "key": 16,
        "type": "double"
      },
      "scaleY": {
        "key": 17,
        "type": "double"
      }
    }
  },
  "TransformComponentConstraint": {
    "typeKey": 85,
    "properties": {
      "minMaxSpaceValue": {
        "key": 195,
        "type": "uint"
      },
      "copyFactor": {
        "key": 182,
        "type": "double"
      },
      "minValue": {
        "key": 183,
        "type": "double"
      },
      "maxValue": {
        "key": 184,
        "type": "double"
      },
      "offset": {
        "key": 188,
        "type": "bool"
      },
      "doesCopy": {
        "key": 189,
        "type": "bool"
      },
      "min": {
        "key": 190,
        "type": "bool"
      },
      "max": {
        "key": 191,
        "type": "bool"
      }
    }
  },
  "TransformComponentConstraintY": {
    "typeKey": 86,
    "properties": {
      "copyFactorY": {
        "key": 185,
        "type": "double"
      },
      "minValueY": {
        "key": 186,
        "type": "double"
      },
      "maxValueY": {
        "key": 187,
        "type": "double"
      },
      "doesCopyY": {
        "key": 192,
        "type": "bool"
      },
      "minY": {
        "key": 193,
        "type": "bool"
      },
      "maxY": {
        "key": 194,
        "type": "bool"
      }
    }
  },
  "TransformConstraint": {
    "typeKey": 83,
    "properties": {
      "originX": {
        "key": 372,
        "type": "double"
      },
      "originY": {
        "key": 373,
        "type": "double"
      }
    }
  },
  "TransformSpaceConstraint": {
    "typeKey": 90,
    "properties": {
      "sourceSpaceValue": {
        "key": 179,
        "type": "uint"
      },
      "destSpaceValue": {
        "key": 180,
        "type": "uint"
      }
    }
  },
  "TransitionArtboardCondition": {
    "typeKey": 497,
    "properties": {}
  },
  "TransitionBoolCondition": {
    "typeKey": 71,
    "properties": {}
  },
  "TransitionComparator": {
    "typeKey": 477,
    "properties": {}
  },
  "TransitionCondition": {
    "typeKey": 476,
    "properties": {}
  },
  "TransitionFocusCondition": {
    "typeKey": 1038,
    "properties": {}
  },
  "TransitionInputCondition": {
    "typeKey": 67,
    "properties": {
      "inputId": {
        "key": 155,
        "type": "uint"
      }
    }
  },
  "TransitionNumberCondition": {
    "typeKey": 70,
    "properties": {
      "value": {
        "key": 157,
        "type": "double"
      }
    }
  },
  "TransitionPropertyArtboardComparator": {
    "typeKey": 496,
    "properties": {
      "propertyType": {
        "key": 677,
        "type": "uint"
      }
    }
  },
  "TransitionPropertyComparator": {
    "typeKey": 478,
    "properties": {}
  },
  "TransitionPropertyComponentComparator": {
    "typeKey": 667,
    "properties": {
      "objectId": {
        "key": 977,
        "type": "uint"
      },
      "propertyKey": {
        "key": 978,
        "type": "uint"
      }
    }
  },
  "TransitionPropertyViewModelComparator": {
    "typeKey": 479,
    "properties": {}
  },
  "TransitionSelfComparator": {
    "typeKey": 593,
    "properties": {}
  },
  "TransitionTriggerCondition": {
    "typeKey": 68,
    "properties": {}
  },
  "TransitionValueArtboardComparator": {
    "typeKey": 630,
    "properties": {}
  },
  "TransitionValueAssetComparator": {
    "typeKey": 602,
    "properties": {}
  },
  "TransitionValueBooleanComparator": {
    "typeKey": 481,
    "properties": {
      "value": {
        "key": 647,
        "type": "bool"
      }
    }
  },
  "TransitionValueColorComparator": {
    "typeKey": 483,
    "properties": {
      "value": {
        "key": 651,
        "type": "color"
      }
    }
  },
  "TransitionValueComparator": {
    "typeKey": 480,
    "properties": {}
  },
  "TransitionValueCondition": {
    "typeKey": 69,
    "properties": {
      "opValue": {
        "key": 156,
        "type": "uint"
      }
    }
  },
  "TransitionValueEnumComparator": {
    "typeKey": 485,
    "properties": {}
  },
  "TransitionValueIdComparator": {
    "typeKey": 601,
    "properties": {
      "value": {
        "key": 653,
        "type": "uint"
      }
    }
  },
  "TransitionValueNumberComparator": {
    "typeKey": 484,
    "properties": {
      "value": {
        "key": 652,
        "type": "double"
      }
    }
  },
  "TransitionValueStringComparator": {
    "typeKey": 486,
    "properties": {
      "value": {
        "key": 654,
        "type": "string"
      }
    }
  },
  "TransitionValueTriggerComparator": {
    "typeKey": 505,
    "properties": {
      "value": {
        "key": 689,
        "type": "uint"
      }
    }
  },
  "TransitionViewModelCondition": {
    "typeKey": 482,
    "properties": {
      "opValue": {
        "key": 650,
        "type": "uint"
      }
    }
  },
  "TranslationConstraint": {
    "typeKey": 87,
    "properties": {}
  },
  "Triangle": {
    "typeKey": 8,
    "properties": {}
  },
  "TrimPath": {
    "typeKey": 47,
    "properties": {
      "start": {
        "key": 114,
        "type": "double"
      },
      "end": {
        "key": 115,
        "type": "double"
      },
      "offset": {
        "key": 116,
        "type": "double"
      },
      "modeValue": {
        "key": 117,
        "type": "uint"
      }
    }
  },
  "UserInput": {
    "typeKey": 663,
    "properties": {}
  },
  "Vertex": {
    "typeKey": 107,
    "properties": {
      "x": {
        "key": 24,
        "type": "double"
      },
      "y": {
        "key": 25,
        "type": "double"
      }
    }
  },
  "ViewModel": {
    "typeKey": 435,
    "properties": {
      "viewModelType": {
        "key": 981,
        "type": "uint"
      }
    }
  },
  "ViewModelComponent": {
    "typeKey": 429,
    "properties": {
      "name": {
        "key": 557,
        "type": "string"
      }
    }
  },
  "ViewModelInstance": {
    "typeKey": 437,
    "properties": {
      "viewModelId": {
        "key": 566,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceArtboard": {
    "typeKey": 599,
    "properties": {
      "propertyValue": {
        "key": 846,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceAsset": {
    "typeKey": 586,
    "properties": {
      "propertyValue": {
        "key": 824,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceAssetBlob": {
    "typeKey": 1044,
    "properties": {}
  },
  "ViewModelInstanceAssetFont": {
    "typeKey": 1035,
    "properties": {}
  },
  "ViewModelInstanceAssetImage": {
    "typeKey": 587,
    "properties": {}
  },
  "ViewModelInstanceBoolean": {
    "typeKey": 449,
    "properties": {
      "propertyValue": {
        "key": 593,
        "type": "bool"
      }
    }
  },
  "ViewModelInstanceColor": {
    "typeKey": 426,
    "properties": {
      "propertyValue": {
        "key": 555,
        "type": "color"
      }
    }
  },
  "ViewModelInstanceEnum": {
    "typeKey": 432,
    "properties": {
      "propertyValue": {
        "key": 560,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceList": {
    "typeKey": 441,
    "properties": {
      "listSource": {
        "key": 966,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceListItem": {
    "typeKey": 427,
    "properties": {
      "viewModelId": {
        "key": 549,
        "type": "uint"
      },
      "viewModelInstanceId": {
        "key": 550,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceNumber": {
    "typeKey": 442,
    "properties": {
      "propertyValue": {
        "key": 575,
        "type": "double"
      }
    }
  },
  "ViewModelInstanceString": {
    "typeKey": 433,
    "properties": {
      "propertyValue": {
        "key": 561,
        "type": "string"
      }
    }
  },
  "ViewModelInstanceSymbol": {
    "typeKey": 565,
    "properties": {}
  },
  "ViewModelInstanceSymbolListIndex": {
    "typeKey": 566,
    "properties": {
      "propertyValue": {
        "key": 814,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceTrigger": {
    "typeKey": 501,
    "properties": {
      "propertyValue": {
        "key": 687,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceValue": {
    "typeKey": 428,
    "properties": {
      "viewModelPropertyId": {
        "key": 554,
        "type": "uint"
      }
    }
  },
  "ViewModelInstanceViewModel": {
    "typeKey": 444,
    "properties": {
      "propertyValue": {
        "key": 577,
        "type": "uint"
      }
    }
  },
  "ViewModelProperty": {
    "typeKey": 430,
    "properties": {
      "symbolTypeValue": {
        "key": 875,
        "type": "uint"
      },
      "componentProps": {
        "key": 957,
        "type": "uint"
      }
    }
  },
  "ViewModelPropertyArtboard": {
    "typeKey": 598,
    "properties": {}
  },
  "ViewModelPropertyAsset": {
    "typeKey": 584,
    "properties": {}
  },
  "ViewModelPropertyAssetBlob": {
    "typeKey": 1043,
    "properties": {}
  },
  "ViewModelPropertyAssetFont": {
    "typeKey": 1034,
    "properties": {}
  },
  "ViewModelPropertyAssetImage": {
    "typeKey": 585,
    "properties": {}
  },
  "ViewModelPropertyBoolean": {
    "typeKey": 448,
    "properties": {}
  },
  "ViewModelPropertyColor": {
    "typeKey": 440,
    "properties": {}
  },
  "ViewModelPropertyEnum": {
    "typeKey": 509,
    "properties": {}
  },
  "ViewModelPropertyEnumCustom": {
    "typeKey": 439,
    "properties": {
      "enumId": {
        "key": 574,
        "type": "uint"
      }
    }
  },
  "ViewModelPropertyEnumSystem": {
    "typeKey": 511,
    "properties": {
      "enumType": {
        "key": 708,
        "type": "uint"
      }
    }
  },
  "ViewModelPropertyList": {
    "typeKey": 434,
    "properties": {}
  },
  "ViewModelPropertyNumber": {
    "typeKey": 431,
    "properties": {}
  },
  "ViewModelPropertyString": {
    "typeKey": 443,
    "properties": {}
  },
  "ViewModelPropertySymbol": {
    "typeKey": 563,
    "properties": {}
  },
  "ViewModelPropertySymbolListIndex": {
    "typeKey": 564,
    "properties": {}
  },
  "ViewModelPropertyTrigger": {
    "typeKey": 502,
    "properties": {}
  },
  "ViewModelPropertyViewModel": {
    "typeKey": 436,
    "properties": {
      "viewModelReferenceId": {
        "key": 565,
        "type": "uint"
      }
    }
  },
  "Weight": {
    "typeKey": 45,
    "properties": {
      "values": {
        "key": 102,
        "type": "uint"
      },
      "indices": {
        "key": 103,
        "type": "uint"
      }
    }
  },
  "WorldTransformComponent": {
    "typeKey": 91,
    "properties": {
      "opacity": {
        "key": 18,
        "type": "double"
      }
    }
  }
};
